openapi: 3.0.3
x-stoplight:
  id: 1p5u246pps3qi
info:
  title: Stats API
  version: 1.0.0-Beta-1
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: Digital Container Shipping Association (DCSA)
    email: info@dcsa.org
    url: 'https://dcsa.org/'
  description: "The Stats API, version 1.0.0, is a service provided by the Digital Container Shipping Association (DCSA). \r\nIt serves as an optional tool for reporting the statistics of a reference API''s usage between peers. \r\nThe aim of the Stats API is to help the DCSA gauge the level of adoption of the reference API, providing vital information that influences future investment and development decisions."
servers:
  - url: 'http://api.dcsa.org'
paths:
  /v1/stats:
    post:
      summary: Publish Stats
      operationId: post-v1-stats
      responses:
        '204':
          description: Accepted
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: POST
                    requestUri: /v1/stats
                    statusCode: 400
                    statusCodeText: Bad Request
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: '2019-11-12T07:41:00+08:30'
                    errors:
                      - errorCode: 7009
                        property: domain
                        value: TNT_NA
                        jsonPath: $.domain
                        errorCodeText: invalidData
                        erorCodeMessage: The domain provided is invalid.
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: POST
                    requestUri: /v1/stats
                    statusCode: 401
                    statusCodeText: Unauthorized
                    statusCodeMessage: Invalid api key
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: '2019-11-12T07:41:00+08:30'
                    errors: []
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: POST
                    requestUri: /v1/stats
                    statusCode: 500
                    statusCodeText: Internal Server Error
                    statusCodeMessage: Unable to process the request.
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: '2019-11-12T07:41:00+08:30'
                    errors: []
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
      description: 'This endpoint allows you to report the usage statistics of a reference API call. '
      parameters:
        - $ref: '#/components/parameters/api-key'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stat'
        description: ''
      tags:
        - RealTime
      x-stoplight:
        id: nh2qnk5aizcue
    parameters: []
  /v1/stats-summary:
    post:
      summary: Stats Summary
      operationId: post-v1-stats-summary
      responses:
        '204':
          description: No Content
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: POST
                    requestUri: /v1/stats
                    statusCode: 400
                    statusCodeText: Bad Request
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: '2019-11-12T07:41:00+08:30'
                    errors:
                      - errorCode: 7009
                        property: domain
                        value: TNT_NA
                        jsonPath: '$.[0].domain'
                        errorCodeText: invalidData
                        erorCodeMessage: The domain provided is invalid.
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: POST
                    requestUri: /v1/stats
                    statusCode: 401
                    statusCodeText: Unauthorized
                    statusCodeMessage: Invalid api key
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: '2019-11-12T07:41:00+08:30'
                    errors: []
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: POST
                    requestUri: /v1/stats
                    statusCode: 500
                    statusCodeText: Internal Server Error
                    statusCodeMessage: Unable to process the request.
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: '2019-11-12T07:41:00+08:30'
                    errors: []
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
      x-stoplight:
        id: 923k81lod9m4g
      requestBody:
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                $ref: '#/components/schemas/StatSummary'
        description: ''
      parameters:
        - $ref: '#/components/parameters/api-key'
      description: This endpoint allows you to report the daily usage statistics of all DCSA APIs being used.
      tags:
        - Summary
components:
  headers:
    API-Version:
      schema:
        type: string
        example: 1.0.0
      description: |
        SemVer used to indicate the version of the contract (API version) returned.
  schemas:
    Stat:
      type: object
      x-stoplight:
        id: 48b7d7d13671d
      properties:
        domain:
          type: string
          enum:
            - TNT
            - TNT_NTF
            - OVS
            - EBL
            - EBL_NTF
            - EBL_SUR
            - EBL_SUR_RSP
            - EBL_ISS
            - EBL_ISS_SUR
            - BKG
            - BKG_NTF
            - CBF
            - JIT
            - CS
            - AN
            - AN_NTF
            - DI
            - DI_NTF
            - RMC
            - RMC_NTF
            - RMO
            - RMO_NTF
            - IC
            - IC_NTF
            - IO
            - IO_NTF
            - DO
            - DO_NTF
            - TO
            - TO_NTF
            - CRO
            - CRO_NTF
          description: |
            The DCSA standard being referred.
            - `TNT` (Track and Trace)
            - `TNT_NTF` (Track and Trace Notifications)
            - `OVS` (Operational Vessel Schedules)
            - `EBL` (Electronic Bill of Lading)
            - `EBL_NTF` (Electronic Bill of Lading Notifications)
            - `EBL_SUR` (Electronic Bill of Lading Surrender)
            - `EBL_SUR_RSP` (Electronic Bill of Lading Surrender Response)
            - `EBL_ISS` (Electronic Bill of Lading Issuance)
            - `EBL_ISS_RSP` (Electronic Bill of Lading Issuance Response)
            - `BKG` (Booking)
            - `BKG_NTF` (Booking Notifications)
            - `CBF` (Consolidated Booking Forecast)
            - `JIT` (Just In Time Portcall)
            - `CS` (Commercial Schedules)
            - `AN` (Arrival Notice)
            - `AN_NTF` (Arrival Notice Notifications)
            - `DI` (Delivery Instruction)
            - `DI_NTF` (Delivery Instruction Notifications)
            - `RMC` (Reefer Monitoring Commercial)
            - `RMC_NTF` (Reefer Monitoring Commercial Notifications)
            - `RMO` (Operational Reefer Monitoring)
            - `RMO_NTF` (Operational Reefer Monitoring Notifications)
            - `IC` (IoT Commercial)
            - `IC_NTF` (IoT Commercial Notifications)
            - `IO` (IoT Operations)
            - `IO_NTF` (IoT Operations Notifications)
            - `DO` (Delivery Order)
            - `DO_NTF` (Delivery Order Notifications)
            - `TO` (Transport Order)
            - `TO_NTF` (Transport Order Notifications)
            - `CRO` (Container Release Order)
            - `CRO_NTF` (Container Release Order Notifications)
        method:
          type: string
          enum:
            - POST
            - GET
            - PUT
            - DELETE
            - PATCH
          example: GET
          description: The HTTP Method used in the referenced API call.
        path:
          type: string
          example: /v2/events
          description: The context path of the reference API call.
          x-stoplight:
            id: 4fkn28q9gaqth
        version:
          type: string
          x-stoplight:
            id: s601oruo9y7da
          example: 2.2.0
          description: DCSA version of the API being used.
        statusCode:
          type: integer
          x-stoplight:
            id: i9k0l00sksmv5
          format: int32
          example: 200
          description: "Http response status code of respective reference call.\r\nFor quality monitoring purposes.  "
        params:
          type: array
          x-stoplight:
            id: kwhdrf20ubqx3
          description: The request query parameters being used.
          minItems: 0
          uniqueItems: true
          example:
            - eventTypes
            - equipmentReference
          items:
            x-stoplight:
              id: ns5q1jn8rh3jx
            type: string
        uniqueAdopterHash:
          type: string
          description: "SHA-256 of the adopter. \r\n\r\n> *Rules to be defined.*"
          x-stoplight:
            id: 9wfo73c55b9mb
          example: ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad
      required:
        - domain
        - method
        - path
        - version
    StatSummary:
      title: StatSummary
      x-stoplight:
        id: zksz5ad1zk3eo
      type: object
      properties:
        date:
          type: string
          x-stoplight:
            id: 5vou2ooc47d7y
          format: date
          example: '2023-11-01'
          description: Statistics created date in `ISO 8601` format.
        domain:
          type: string
          enum:
            - TNT
            - TNT_NTF
            - OVS
            - EBL
            - EBL_NTF
            - EBL_SUR
            - EBL_SUR_RSP
            - EBL_ISS
            - EBL_ISS_SUR
            - BKG
            - BKG_NTF
            - CBF
            - JIT
            - CS
            - AN
            - AN_NTF
            - DI
            - DI_NTF
            - RMC
            - RMC_NTF
            - RMO
            - RMO_NTF
            - IC
            - IC_NTF
            - IO
            - IO_NTF
            - DO
            - DO_NTF
            - TO
            - TO_NTF
            - CRO
            - CRO_NTF
          description: |
            The DCSA standard being referred.
            - `TNT` (Track and Trace)
            - `TNT_NTF` (Track and Trace Notifications)
            - `OVS` (Operational Vessel Schedules)
            - `EBL` (Electronic Bill of Lading)
            - `EBL_NTF` (Electronic Bill of Lading Notifications)
            - `EBL_SUR` (Electronic Bill of Lading Surrender)
            - `EBL_SUR_RSP` (Electronic Bill of Lading Surrender Response)
            - `EBL_ISS` (Electronic Bill of Lading Issuance)
            - `EBL_ISS_RSP` (Electronic Bill of Lading Issuance Response)
            - `BKG` (Booking)
            - `BKG_NTF` (Booking Notifications)
            - `CBF` (Consolidated Booking Forecast)
            - `JIT` (Just In Time Portcall)
            - `CS` (Commercial Schedules)
            - `AN` (Arrival Notice)
            - `AN_NTF` (Arrival Notice Notifications)
            - `DI` (Delivery Instruction)
            - `DI_NTF` (Delivery Instruction Notifications)
            - `RMC` (Reefer Monitoring Commercial)
            - `RMC_NTF` (Reefer Monitoring Commercial Notifications)
            - `RMO` (Operational Reefer Monitoring)
            - `RMO_NTF` (Operational Reefer Monitoring Notifications)
            - `IC` (IoT Commercial)
            - `IC_NTF` (IoT Commercial Notifications)
            - `IO` (IoT Operations)
            - `IO_NTF` (IoT Operations Notifications)
            - `DO` (Delivery Order)
            - `DO_NTF` (Delivery Order Notifications)
            - `TO` (Transport Order)
            - `TO_NTF` (Transport Order Notifications)
            - `CRO` (Container Release Order)
            - `CRO_NTF` (Container Release Order Notifications)
          example: TNT
        stats:
          type: array
          x-stoplight:
            id: cdq77937fsie1
          items:
            x-stoplight:
              id: 1p1hne8vh8ih2
            type: object
            properties:
              method:
                type: string
                enum:
                  - POST
                  - GET
                  - PUT
                  - DELETE
                  - PATCH
                example: GET
                description: The HTTP Method used in the referenced API call.
              path:
                type: string
                example: /v2/events
                description: The context path of the referenced API call.
                x-stoplight:
                  id: dd7uu577vzfoh
              version:
                x-stoplight:
                  id: 0lnt7kibij7ru
                type: string
                example: 2.2.0
                description: DCSA version of the API being used.
              params:
                type: array
                x-stoplight:
                  id: 3qw6pb51no9eq
                minItems: 0
                description: Unique set of request parameters being used for the referenced API.
                example:
                  - eventTypes
                  - equipmentReference
                items:
                  x-stoplight:
                    id: 90u9gigs8b6dv
                  type: string
              totalApiRequests:
                type: integer
                x-stoplight:
                  id: rfkm8ldsyylnz
                description: Total request count for the day for the referenced API.
                example: 1000000
                format: int64
              totalSuccessRequests:
                type: integer
                x-stoplight:
                  id: tyokdnx3ee34j
                format: int64
                description: "Total success request count for the day for the referenced API.\r\n\r\nResponses considered successful : `200`, `201`, `202`, `204`"
                example: 900000
              totalFailureRequests:
                type: integer
                x-stoplight:
                  id: 3w9rlh3b1chwb
                format: int64
                description: Total failure request count for the day for the referenced API.
                example: 100000
                minimum: 0
              avgResponseTime:
                type: integer
                x-stoplight:
                  id: oafrnp48rl4bl
                format: int64
                description: Average response time for the referenced API in `milliseconds`.
                example: 437
              uniqueAdopterCount:
                type: integer
                x-stoplight:
                  id: fukl7u6zkokz4
                format: int64
                example: 20
                description: Number of unique adopters using the standard.
                minimum: 0
                exclusiveMinimum: true
            required:
              - method
              - version
              - totalApiRequests
              - uniqueAdopterCount
      required:
        - date
        - domain
        - stats
    ErrorResponse:
      title: Error Response
      x-stoplight:
        id: bmembi2njjjlv
      type: object
      description: Unexpected error
      properties:
        httpMethod:
          description: |
            The HTTP method used to make the request e.g. `GET`, `POST`, etc
          type: string
          example: POST
          enum:
            - GET
            - HEAD
            - POST
            - PUT
            - DELETE
            - OPTION
            - PATCH
        requestUri:
          description: |
            The URI that was requested.
          type: string
          example: /v1/stats
        statusCode:
          description: |
            The HTTP status code returned.
          type: integer
          format: int32
          example: 400
        statusCodeText:
          description: |
            A standard short description corresponding to the HTTP status code.
          type: string
          maxLength: 50
          example: Bad Request
        statusCodeMessage:
          description: |
            A long description corresponding to the HTTP status code with additional information.
          type: string
          maxLength: 200
        providerCorrelationReference:
          description: |
            A unique identifier to the HTTP request within the scope of the API provider.
          type: string
          maxLength: 100
          example: 4426d965-0dd8-4005-8c63-dc68b01c4962
        errorDateTime:
          description: |
            The DateTime corresponding to the error occuring. Must be formatted using [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
          type: string
          format: date-time
          example: '2019-11-12T07:41:00+08:30'
        errors:
          type: array
          description: |
            An array of errors provding more detail about the root cause.
          minItems: 0
          items:
            type: object
            title: Detailed Error
            properties:
              errorCode:
                type: integer
                format: int32
                description: |
                  The detailed error code returned.

                    - `7000-7999` Technical error codes
                    - `8000-8999` Functional error codes
                    - `9000-9999` API provider-specific error codes            

                  [Error codes as specified by DCSA](https://dcsa.atlassian.net/wiki/spaces/DTG/pages/197132308/Standard+Error+Codes).
                minimum: 7000
                maximum: 9999
                example: 7003
              property:
                type: string
                maxLength: 100
                description: |
                  The name of the property causing the error.
                example: domain
              value:
                type: string
                maxLength: 500
                description: |
                  The value of the property causing the error serialised as a string exactly as in the original request.
                example: TNT_NA
              jsonPath:
                type: string
                maxLength: 500
                description: |
                  A path to the property causing the error, formatted according to [JSONpath](https://github.com/json-path/JsonPath).
                example: $.domain
              errorCodeText:
                description: |
                  A standard short description corresponding to the `errorCode`.
                type: string
                maxLength: 100
                example: invalidData
              erorCodeMessage:
                type: string
                maxLength: 200
                description: |
                  A long description corresponding to the `errorCode` with additional information.
                example: The domain provided is invalid.
            required:
              - errorCodeText
      required:
        - httpMethod
        - requestUri
        - statusCode
        - statusCodeText
        - errorDateTime
        - errors
  parameters:
    api-key:
      name: DCSA-API-KEY
      in: header
      required: true
      schema:
        type: string
        example: 055409d4-c69a-403f-8cca-d950fc11b12b
        format: uuid
      description: An API key for authorizing requests.
tags:
  - name: RealTime
    description: The real time stats
  - name: Summary
    description: The summary stats
